### ISSUE TITLE
Redis Konfiguration

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/docker-compose-scanners#1]
Um eine Redis-Instanz als Cache und Queue-List nutzen zu können, müssen die jeweiligen Scanner ein eindeutiges Prefix nutzen:

- [x] HSHS-DOMXSS-Scanner
- [x] Version-Scanner
- [x] Core-API
- [ ] InfoLeak-Scanner (Queue is still missing)
- [ ] Blacklist-Scanner (wird redis genutzt?)

**Comment by SniperSister** [comment]
Wäre eine eigene DB ID je Scanner nicht sinnvoller und einfacher in der Implementierung? Laravel hat dafür z.B einen env Parameter.

**Comment by Lednerb** [comment]
Das wäre eine Option für die Queue, aber wie sieht es mit dem Cache aus?

Bspw. wenn wir die `config:cache` Option nutzten um etwas mehr Geschwindigkeit zu bekommen, dann müsste der Cache auch je Scanner / Projekt genutzt werden

**Comment by SniperSister** [comment]
Denke das müssen wir schlicht testen

**Comment by Lednerb** [comment]
Passt perfekt.

Unter `config/database.php` lassen sich die redis Einstellungen für cache und queue über die jeweiligen Parameter `REDIS_DB=0` und `REDIS_CACHE_DB=1` einstellen.

[Standardmäßig](http://download.redis.io/redis-stable/redis.conf) stellt Redis 16 Datenbanken zur verfügung:

    # Set the number of databases. The default database is DB 0, you can select
    # a different one on a per-connection basis using SELECT <dbid> where
    # dbid is a number between 0 and 'databases'-1
    databases 16
